cloud:
  aws:
    s3:
      bucket: h010gram
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIA6DLGUIKSG7PKW3UO
      secret-key: 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